language: python

python:
  - "3.6"

install:
  - pip install --upgrade pip; pip install -r requirements.txt
  - python setup.py install

script:
  - cd test; pytest --disable-warnings --cov=dvt --cov-report term-missing .
  - codecov
