dist: xenial
language: python

python:
  - "3.7"

install:
  - pip install --upgrade pip; pip install -r requirements.txt
  - pip install -U pytest
  - python setup.py install

script:
  - cd tests; pytest --disable-warnings --cov=dvt --cov-report term-missing .
  - cd tests; codecov
