dist: xenial
language: python

python:
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install .[tests,optional]

script:
  - cd tests; pytest --disable-warnings --cov=dvt --cov-report term-missing .
  - cd tests; codecov
